### ISSUE TITLE
Creation of multiple topic_interest

### ISSUE THREAD

**Issue by moissinac** [jmvanel/semantic_forms#108] opened 2016-11-06 16:07 UTC
Having created an entity of type foaf:Person, I have added a topic_interest
Then, when I want to add another topic_interest, by clicking the + button, SemanticForm éditor of entity quit the editing mode and go to the display mode. I'm unable to add a new topic_interest

**Comment by moissinac** [comment] 2016-11-06 16:12
In the console, after clicking the +, there is a lot of traces ending by
IP addresses:
Interface name: WAN Miniport (IPv6)-QoS Packet Scheduler-0000
Device: eth17
Is loopback: false
Is up: false
Is p2p: false
Is virtual: false
Supports multicast: true
IP addresses:
Interface name: WAN Miniport (Network Monitor)-WFP Native MAC Layer LightWeight Filter-0000
Device: eth18
Is loopback: false
Is up: false
Is p2p: false
Is virtual: false
Supports multicast: true
IP addresses:
Interface name: WAN Miniport (Network Monitor)-QoS Packet Scheduler-0000
Device: eth19
Is loopback: false
Is up: false
Is p2p: false
Is virtual: false
Supports multicast: true
IP addresses:
ni name:lo (Software Loopback Interface 1) hostAddress 127.0.0.1
ni name:lo (Software Loopback Interface 1) hostAddress 0:0:0:0:0:0:0:1
ni name:wlan0 (Intel(R) Dual Band Wireless-AC 7260) hostAddress 192.168.3.20
ni name:wlan0 (Intel(R) Dual Band Wireless-AC 7260) hostAddress 2a01:e35:8beb:4070:ed3c:9eaa:560:a11
ni name:wlan0 (Intel(R) Dual Band Wireless-AC 7260) hostAddress 2a01:e35:8beb:4070:804:e6d0:933a:acd5
ni name:wlan0 (Intel(R) Dual Band Wireless-AC 7260) hostAddress fe80:0:0:0:ed3c:9eaa:560:a11%wlan0
ni name:net3 (Microsoft ISATAP Adapter) hostAddress fe80:0:0:0:0:5efe:c0a8:3801%net3
ni name:eth3 (Bluetooth Device (Personal Area Network)) hostAddress fe80:0:0:0:258c:d0c:318b:bc3a%eth3
ni name:eth4 (VirtualBox Host-Only Ethernet Adapter) hostAddress 192.168.56.1
ni name:eth4 (VirtualBox Host-Only Ethernet Adapter) hostAddress fe80:0:0:0:f5e9:60c2:ab04:d02a%eth4
ni name:net7 (Microsoft Teredo Tunneling Adapter) hostAddress fe80:0:0:0:0:100:7f:fffe%net7
ni name:wlan1 (Carte virtuelle directe Wi-Fi Microsoft) hostAddress fe80:0:0:0:e9d4:c50a:c66:951f%wlan1
ni name:net9 (Microsoft ISATAP Adapter #4) hostAddress fe80:0:0:0:0:5efe:c0a8:314%net9
intranetAdresses List(/192.168.3.20, /192.168.56.1)
internetAdresses List()
CAUTION: several Internet Adresses: List(/192.168.3.20, /192.168.56.1)
hostNameUsed http:///192.168.3.20
Retrieving default port from config.
def login request GET /login,
      cookies Map(PLAY_SESSION -> Cookie(PLAY_SESSION,83720c30c148209ce018a524f3fd1e3f2a2e1e4b-to-redirect=%2Fldp%2F1478443469577-148349862844154,None,/,None,false,true))
Graph at URI http://127.0.0.1:9000/ldp/1478443469577-148349862844154 could not be downloaded, trying local TDB (Failed to determine the content type: (URI=http://127.0.0.1:9000/ldp/1478443469577-148349862844154 : stream=text/html)).
search_only
CONSTRUCT {
  <http://127.0.0.1:9000/ldp/1478443469577-148349862844154> ?p ?o .
  ?thing ?p ?o .
  ?s ?p1 <http://127.0.0.1:9000/ldp/1478443469577-148349862844154> .
}
WHERE {
  GRAPH ?GRAPH
  { <http://127.0.0.1:9000/ldp/1478443469577-148349862844154> ?p ?o . }
  OPTIONAL {
    GRAPH <http://127.0.0.1:9000/ldp/1478443469577-148349862844154>
    { ?thing ?p ?o . }
    GRAPH ?GRAPH2
    { ?s ?p1 <http://127.0.0.1:9000/ldp/1478443469577-148349862844154> . } # "reverse" triples
  }
}
sparqlConstructQuery: before parseConstruct
sparqlConstructQuery: before executeConstruct
search_only: after sparqlConstructQuery
2016-11-06 17:09:46 INFO  root     - After retrieveURINoTransaction(makeUri(http://127.0.0.1:9000/ldp/1478443469577-148349862844154), store)
TableViewModule.graf2form(graph: graph :  {moissinac @urn:displayLabel "moissinac#"; http://xmlns.com/foaf/0.1/Person @urn:displayLabel "Person"; http://xmlns.com/foaf/0.1/Person @http://www.w3.org/2003/06/sw-vocab-status/ns#term_status "stable"; http://xmlns.com/foaf/0.1/Person @http://www.w3.org/2000/01/rdf-schema#label "Person"; http://xmlns.com/foaf/0.1/Person @http://www.w3.org/2000/01/rdf-schema#isDefinedBy http://xmlns.com/foaf/0.1/; http://xmlns.com/foaf/0.1/Person @http://www.w3.org/2000/01/rdf-schema#comment "A person."; http://xmlns.com/foaf/0.1/Person @http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://www.w3.org/2002/07/owl#Class; http://xmlns.com/foaf/0.1/Person @http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://www.w3.org/2000/01/rdf-schema#Class; http://xmlns.com/foaf/0.1/Person @http://www.w3.org/2002/07/owl#disjointWith http://xmlns.com/foaf/0.1/Project; http://xmlns.com/foaf/0.1/Person @http://www.w3.org/2002/07/owl#disjointWith http://xmlns.com/foaf/0.1/Organization; http://xmlns.com/foaf/0.1/Person @http://www.w3.org/2000/01/rdf-schema#subClassOf http://xmlns.com/foaf/0.1/Agent; http://xmlns.com/foaf/0.1/Person @http://www.w3.org/2000/01/rdf-schema#subClassOf http://www.w3.org/2003/01/geo/wgs84_pos#SpatialThing; http://xmlns.com/foaf/0.1/Person @http://www.w3.org/2000/01/rdf-schema#subClassOf http://www.w3.org/2000/10/swap/pim/contact#Person; http://xmlns.com/foaf/0.1/knows @http://www.w3.org/2003/06/sw-vocab-status/ns#term_status "stable"; http://xmlns.com/foaf/0.1/knows @http://www.w3.org/2000/01/rdf-schema#range http://xmlns.com/foaf/0.1/Person; http://xmlns.com/foaf/0.1/knows @http://www.w3.org/2000/01/rdf-schema#label "knows"; http://xmlns.com/foaf/0.1/knows @http://www.w3.org/2000/01/rdf-schema#isDefinedBy http://xmlns.com/foaf/0.1/...}, graphURI <moissinac>
lookFormSpecInConfiguration: found for http://xmlns.com/foaf/0.1/Person None
FormSyntaxFactory: preferedLanguage: fr
WARNING: There is no range for property http://www.w3.org/2000/01/rdf-schema#label
WARNING: There is no range for property http://www.w3.org/2000/01/rdf-schema#comment
WARNING: There is no range for property http://www.w3.org/1999/02/22-rdf-syntax-ns#type

**Comment by jmvanel** [comment] 2016-11-06 16:36
Sorry,
I cannot reproduce the issue,
and the logs do not help.

I don't have a Microsoft machine at hand,
but I'll ask Romain to check that.

We need to know : 

1. - the brand and version of the browser
2. - the OS version
3. - the java JMV version

The browser is I think the first "suspect" , and it would be interesting to try another of the big 3: FF, Chrome, IE.

**Comment by moissinac** [comment] 2016-11-06 18:14
OS Windows 10 version 1607
Java 1.8.0 VM 25.101
Essai 1: Chrome Version 54.0.2840.87 m
Essai 2: Firefox version 49.0.1
Essai 3: Internet Explorer 11.321
Essai 4: Edge Microsoft Edge 38.14393.0.0

Same result in all cases
Perhaps a misunderstanding on how to use the tool?

**Comment by jmvanel** [comment] 2016-11-06 18:22
OK, now we see it's probably a Windows issue.

To check that's it's not a misunderstanding on how to use the tool, you can try on the sandbox, which is very close to the release:
http://163.172.179.125:9111/create?uri=&uri=http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FPerson

Multiple values on the interest field have been used by many people for months, but on a hosted Linux machine like the sandbox.

**Comment by moissinac** [comment] 2016-11-06 18:36
The sandbox seems different.
My local version wait for an URI in the topic_interest field
The sandbox wait for an english word in the 'sujet d'intérêt' field
When I directly type an URI in both, after saving the entity, the lable of the URI appears with a # at the end (ex: Paris# for http://fr.dbpedia.org/resource/Paris entered in the field)
The sandbox seems to work either entering Paris or http://fr.dbpedia.org/resource/Paris

**Comment by jmvanel** [comment] 2016-11-06 21:18
If you did not run PopulateRDFCache , you have not loaded the default form specifications,
which  tell the application which are the fields for dbPedia lookup.

FYI the default form specifications are in:
https://github.com/jmvanel/semantic_forms/tree/master/scala/forms/form_specs

**Comment by weeger** [comment] 2016-11-21 11:51
Reproduced! (sorry for the delay)

We could see it together when you come back @jmvanel

**Comment by jmvanel** [comment] 2017-01-17 09:25
The completion with dbPedia lookup is triggered by a form specification item, like:
```turtle
forms:topic_interest
	:fieldAppliesToForm forms:personForm ;
	:fieldAppliesToForm forms:organizationForm ;
	:fieldAppliesToProperty foaf:topic_interest ;
:widgetClass form:DBPediaLookup .
```
in https://github.com/jmvanel/semantic_forms/blob/master/scala/forms/form_specs/foaf.form.ttl#L35

Such a form specification can be loaded:
1. directly by pasting the "[raw URL](https://raw.githubusercontent.com/jmvanel/semantic_forms/master/scala/forms/form_specs/foaf.form.ttl)" in top display field
2. or with a large group of ontologies , by running PopulateRDFCache , see
https://github.com/jmvanel/semantic_forms/blob/master/doc/en/administration.md#preloading-rdf-content

**Comment by jmvanel** [comment] 2017-01-17 09:28
About the other problem you reported , "clicking the + button, SemanticForm editor of entity quit the editing mode and go to the display mode" ,
this seems a browser specific issue.

Which browser is it ?
Semantic_Forms has been tested with recent Forefix and Chromium,
ocasionnaly on Android browser.

**Comment by jmvanel** [comment] 2017-09-19 14:21
Adding  type="button" in `<button>` was absolutely necessary per the HTML standard.
Closing the issue.

**Closed by jmvanel** 2017-09-19 14:21 UTC
